# Generated by Django 6.0.5 on 2026-06-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberFraudQuizSite', '0003_alter_result_score_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=100, verbose_name='Заголовок вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст вопроса'),
        ),
    ]
