upstream django_app {
    server web:8000;
}

server {
    listen 80;

    access_log /var/log/nginx/CyberFraudQuiz_access.log;
    error_log /var/log/nginx/CyberFraudQuiz_error.log;

    location /static/ {
        alias /opt/CyberFraudQuiz/staticfiles/;
        expires 30d;
    }

    location / {
        include proxy_params;
        proxy_pass http://django_app;
    }
}
