# Generated by Django 6.0.5 on 2026-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='Заголовок вопроса')),
                ('text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('options', models.JSONField(verbose_name='Варианты ответов')),
                ('score', models.JSONField(verbose_name='Количество баллов')),
                ('explanation', models.JSONField(verbose_name='Объяснение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
