name: Build & push to ghcr.io

on:
  push:
    branches: [ "develop" ]  # Запускается при пуше в develop
  pull_request:
    branches: [ "develop" ] # Запускается при создании PR в develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cyber_fraud_quiz:latest